cluster:
  v_node_count: 100
  replicas: 2

messaging:
  gossip_peer_count: 2
  message_timeout: 1s
  message_retry: 3
  heartbeat_interval: 3s

rebalance:
  rebalance_debounce: 1s

persistence:
  persistence_interval: 10s

maintenance:
  cleanup_interval: 10s