cluster:
  v_node_count: 100
  replicas: 1

messaging:
  gossip_peer_count: 2
  message_timeout: 3s
  message_retry: 3
  heartbeat_interval: 3s

rebalance:
  rebalance_debounce: 1s

persistence:
  persistence_interval: 1m
  restore_on_startup: auto

maintenance:
  cleanup_interval: 10s